name: Scorecard

on:
  push:
    branches:
      - main

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Scorecard
        uses: ossf/scorecard-action@v1  # Use v1 if v2 fails
