name: Scorecard

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Scorecard
        uses: ossf/scorecard-action@v2
